name: Udacity-DevOps-P3

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - main

pool:
  name: 'Azure Pipelines'

variables:
  pythonVersion: '3.7'
  azureServiceConnectionId: 'Udacity-DevOps-P3'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: "Test"

stages:
  #--------------------------------------------#
  # Use Terraform to create the Infrastructure
  - stage: Infrastructure
    displayName: "Create Infrastructure"
    jobs:
      - job: Infrastructure
        displayName: "Create the Infrastructure"
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '$(pythonVersion)'
            displayName: 'Use Python $(pythonVersion)'

          - task: CmdLine@2
            displayName: 'Install Terraform'
            inputs: 
              script: |
                curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
                sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
                sudo apt-get update && sudo apt-get install terraform -y

          - checkout: self
            displayName: 'Checkout Source'

          - task: CmdLine@2
            displayName: 'Terraform Apply/Refresh'
            inputs:
              script: |
                terraform init
                terraform plan -out=tfplan
                terraform apply tfplan || terraform refresh
              workingDirectory: "$(projectRoot)/terraform/environments/test"
  
  #--------------------------------------------#
  - stage: Build
    displayName: "Build Packages"
    dependsOn: Infrastructure
    condition: succeeded()
    jobs:
      - job: BuildFakeRestAPI
        displayName: "Build FakeRestAPI"
        steps:
          - checkout: self
            displayName: 'Checkout Source'
          
          - task: ArchiveFiles@2
            displayName: 'Archive FakeRestAPI'
            inputs:
              rootFolderOrFile: "$(projectRoot)/automatedtesting/jmeter/fakerestapi"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip"

          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
            displayName: 'Upload Package FakeRestAPI'
            artifact: drop-fakerestapi

      - job: BuildSelenium
        displayName: "Build Selenium Package"
        steps:
          # Selenium Test Suite - Archive the package
          - task: ArchiveFiles@2
            displayName: 'Archive UI Tests'
            inputs:
              rootFolderOrFile: "$(projectRoot)/automatedtesting/selenium"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip"
          
          # Selenium Test Suite - Publish the package
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-uitests.zip # Same as the archiveFile artifact above.
            displayName: 'Upload Package UI Tests'
            artifact: drop-uitests
      
      - job: BuildJMeter
        displayName: "Build JMeter Package"
        steps:
          - task: ArchiveFiles@2
            displayName: 'Archive PerformanceTestSuite'
            inputs:
              rootFolderOrFile: "$(projectRoot)/automatedtesting/jmeter/perftests"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perftests.zip"
          
          # JMeter Test Suite - Publish
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-perftests.zip
            displayName: 'Upload Package PerformanceTestSuite'
            artifact: drop-perftests
  
  - stage: Deploy
    displayName: "Deploy Package"
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: FakeRestAPI
        displayName: 'Deploy FakeRestAPI'
        pool:
          vmImage: "ubuntu-latest"
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy FakeRestAPI'
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Udacity-DevOps-P3'
                    appType: 'webApp'
                    WebAppName: 'udacity-devops-p3-AppService'
                    packageForLinux: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'

  - stage: Testing
    displayName: "Test Package"
    dependsOn: Deploy
    condition: succeeded()
    jobs:
      - job: TestPostman
        displayName: 'Test FakeRestAPI With Postman'
        steps:
          - checkout: self
            displayName: 'Checkout Source'

          # Postman - Install Newman
          - task: CmdLine@2
            displayName: Install Newman
            inputs:
              script: "sudo npm install -g newman"
              workingDirectory: $(projectRoot)

          # Postman Data Validation Test Suite
          - task: CmdLine@2
            displayName: Run Data Validation Tests
            continueOnError: true
            inputs:
              script: 'newman run TestSuite.Data-Validation.json -e Test.environment.json --reporters cli,junit --reporter-junit-export TEST-DataValidation.xml'
              workingDirectory: '$(projectRoot)/automatedtesting/postman'

          # Postman Regression Test Suite
          - task: CmdLine@2
            displayName: Run Regression Tests
            continueOnError: true
            inputs:
              script: 'newman run TestSuite.Regression.json -e Test.environment.json --reporters cli,junit --reporter-junit-export TEST-Regression.xml'
              workingDirectory: '$(projectRoot)/automatedtesting/postman'

          # Postman - Publish Results
          - task: PublishTestResults@2
            displayName: Publish Test Results
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "**/TEST-*.xml"
              searchFolder: '$(projectRoot)/automatedtesting/postman'
              mergeTestResults: true
              testRunTitle: "Postman - Publish Results"

      - job: TestJMeter
        displayName: 'Test FakeRestAPI With JMeter'
        steps:
          # Run JMeter test suite against the App Service
          - task: CmdLine@2
            displayName: 'Run JMeter test suite against the App Service'
            inputs:
              script: |
                wget "https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz"
                tar -xf apache-jmeter-5.6.2.tgz
                unzip -o $(Build.BuildId)-perftests.zip
                ./apache-jmeter-5.6.2/bin/jmeter -n -t PerformanceTestSuite.jmx -j jmeter.log -f
                cat jmeter.log
              workingDirectory: $(Pipeline.Workspace)/drop-perftests

      - deployment: VMDeploy
        displayName: 'Selenium Tests'
        environment:
          name: $(environmentName)
          resourceType: VirtualMachine
          tags: selenium
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: 'Download Selenium Package'
                  artifact: drop-uitests

                - task: Bash@3
                  displayName: 'Run Selenium Functional UI Tests'
                  inputs:
                    targetType: "inline"
                    script: |
                      #! /bin/bash
                      sudo apt-get upgrade -y
                      sudo apt-get install python3-pip -y
                      sudo apt-get install unzip -y
                      sudo apt-get install -y chromium-browser
                      pip3 install selenium
                      cd ~/
                      DIR=/home/testuser/app
                      if [ ! -d "$DIR" ]; then
                          mkdir app
                      fi
                      mv /home/testuser/azagent/_work/1/drop-uitests/$(Build.BuildId)-uitests.zip app
                      cd app
                      unzip -o $(Build.BuildId)-uitests.zip
                      FILE=/home/testuser/app/chromedriver_linux64.zip
                      if [ ! -f "$FILE" ]; then
                          LATEST=$(wget -q -O - http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
                          wget http://chromedriver.storage.googleapis.com/$LATEST/chromedriver_linux64.zip
                          unzip -o chromedriver_linux64.zip
                          sudo ln -s $PWD/chromedriver /usr/local/bin/chromedriver
                      fi
                      export PATH=$PATH:/home/testuser/app
                      echo "Starting Selenium Tests"
                      python3 add_remove_from_cart.py >> selenium.log
                      echo "Completed Selenium Tests. Check selenium.log for results."
