name: Udacity-DevOps-P3

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - test

pool:
  name: "Azure Pipelines"

variables:
  pythonVersion: "3.7"
  azureServiceConnectionId: "Udacity-DevOps-P3"
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: "Test"

steps:
  - checkout: self
    displayName: "Checkout Source"

  - task: AzureCLI@2
    displayName: 'Azure CLI - Connect to VM'
    inputs:
      azureSubscription: 'Udacity-DevOps-P3'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az vm run-command invoke -g rs-Udacity-DevOps-P3 -n udacity-devops-p3-LinuxVirtualMachine --command-id RunShellScript --scripts "echo Connected to VM"'

  - script: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser
      sudo apt-get install -y chromium-chromedriver
    displayName: 'Install Chrome and ChromeDriver'

  - script: |
      wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
    displayName: 'Install and configure Selenium Server'

  - task: CopyFiles@2
    displayName: 'Copy Selenium dependencies to Azure VM'
    inputs:
      SourceFolder: '$(projectRoot)/automatedtesting/selenium'
      Contents: '**'
      TargetFolder: '/home/adminuser/selenium'  # Destination path on the Azure VM

  - script: |
      cd /home/adminuser/selenium
      python3 add_remove_from_cart.py >> selenium.log
    displayName: 'Run Selenium tests on Azure VM'